@url = http://localhost:3000

### Login
# @name login
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "aaaa@gmail.com",
  "password": "Test1234"
}

###
@token = {{login.response.body.token}}

### lista de usuarios
GET {{url}}/usuarios
Authorization: Bearer {{token}}

### obtener usuario por ID
GET {{url}}/usuarios/1
Authorization: Bearer {{token}}

### modificar usuario
PUT {{url}}/usuarios/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nombre": "AgusMod",
  "email": "agusmod@example.com"
}

### eliminar usuario
DELETE {{url}}/usuarios/7
Authorization: Bearer {{token}}
